apiVersion: v1
kind: Service
metadata:
  name: egress-ssh
  labels:
    app.kubernetes.io/name: minicloud
    app.kubernetes.io/component: egress-ssh
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: egress-ssh
  ports:
    - name: http
      port: 8080
      targetPort: http
