apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-data
  labels:
    app.kubernetes.io/name: minicloud
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard   # uncomment to pin a specific storage class
