apiVersion: v1
kind: Service
metadata:
  name: xslt
  labels:
    app.kubernetes.io/name: minicloud
    app.kubernetes.io/component: xslt
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: xslt
  ports:
    - name: http
      port: 8080
      targetPort: http
