name: test.messageservice.publish.0.1
group: Integration
invocation:
  allow_http: false
  allow_schedule: true
steps:
  - id: store_inbound_message
    type: storage_write
    storage:
      bucket: demo
      key: rabbitmq/subscriber_last
      value_from: initial
